# Generated by Django 5.2.7 on 2025-10-31 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippets',
            old_name='lineons',
            new_name='linenos',
        ),
    ]
